name: trilochanaa_app
description: A new Flutter project.


publish_to: 'none'
version: 1.0.6+6

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_barcode_scanner: ^2.0.0
  http: ^1.2.1
  shared_preferences: ^2.0.12
  cached_network_image: ^3.3.0
  email_validator: ^2.1.2
  shimmer: ^3.0.0
  file_picker: ^6.1.1
  get_storage: ^2.0.3
  flag: ^7.0.0
  url_launcher:
  intl:
  image_picker:
  path:
  rflutter_alert: ^2.0.7
  date_time_picker: ^2.1.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.9
  firebase_core_platform_interface: ^5.0.0
  fluttertoast: ^8.0.8
  flutter_svg: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/icon.png"
  android: "launcher_icon"
  iso: true

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/

flutter_native_splash:
  color: "#002793"
  image: assets/images/icon.png
  android: true
  ios: false